name: fast_network
description: Network Encapsulation Library
version: 1.0.5
homepage: https://github.com/kangjianqun/fast_network

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.flutter-io.cn/packages/fast_utils
  fast_utils: ^1.0.3
  # https://pub.flutter-io.cn/packages/dio
  dio: ^5.1.1
  dio_cookie_manager: ^3.0.0
  dio_http2_adapter: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
