name: fast_net
description: Network Encapsulation Library
version: 1.0.0
homepage: https://github.com/kangjianqun/fast_net

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.flutter-io.cn/packages/fast_utils
  fast_utils: ^1.0.1
  # https://pub.flutter-io.cn/packages/package_info_plus
  package_info_plus: ^1.4.3
  # https://pub.flutter-io.cn/packages/dio
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  dio_http2_adapter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
